server.port=11005

spring.kafka.consumer.bootstrap-servers=192.168.1.201:9092
spring.kafka.consumer.group-id=risk-service-2
spring.kafka.consumer.listen-topics=android_fact_start,android_fact_device,android_fact_net,android_fact_self-app,android_fact_file,android_fact_runtime,android_fact_app,android_fact_location,android_fact_inject,android_fact_event,android_fact_java,android_fact_native,android_fact_anr,android_fact_activity,android_fact_url,android_fact_user,android_fact_privacy,h5_fact_start,h5_fact_device,h5_fact_self_app,h5_fact_runtime,h5_fact_location,h5_fact_event,h5_fact_error,h5_fact_dev_tool,h5_fact_debug,h5_fact_user,ios_fact_start,ios_fact_device,ios_fact_net,ios_fact_self-app,ios_fact_file,ios_fact_runtime,ios_fact_app,ios_fact_location,ios_fact_inject,ios_fact_view,ios_fact_signal,ios_fact_objc,ios_fact_user,host_fact_start,host_fact_device,host_fact_file,host_fact_net,host_fact_runtime,host_fact_event,host_fact_user,wechat_fact_start,wechat_fact_device,wechat_fact_user

spring.data.redis.database=0
spring.data.redis.host=192.168.1.201
spring.data.redis.port=6379
spring.data.redis.password=XmSX6jCpHNB5tsmw8QXn

rating.data.expire.days=30
rating.rule.config.path=/Users/yaoqi.li/Documents/cabin/coolxer/x-genie/rating-service/src/main/resources/rating_config/rating_rule.json

spring.kafka.bootstrap-servers=192.168.1.201:9092
spring.kafka.producer.properties.partitioner.class=com.coolxer.risk.configuration.KeyHashPartitioner
kafka.topic.partitions=1
kafka.topic.replicas=1

spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=30

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
