global:
  version: latest

embedded:
  mysql:
    enabled: true
  clickhouse:
    enabled: true
  redis:
    enabled: true
  redisStack:
    enabled: true
  kafka:
    enabled: true

ingress:
  enabled: false
