global:
  version: latest

vectum:
  image:
    version: "1.0.1"

embedded:
  mysql:
    enabled: true
  clickhouse:
    enabled: true
  redis:
    enabled: true
  redisStack:
    enabled: true
  kafka:
    enabled: true

ingress:
  enabled: false
